## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/obophenotype for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull
    
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - test-travis

notifications:
  email:
    recipients:
      - nicolas.matentzoglu@gmail.com
    on_success: change
    on_failure: always

# perform quality checks
script: 
  - cd src/ontology && sh run.sh make test
