sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && sh run0.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

### Add your own lists here
### See https://github.com/INCATools/ontology-starter-kit/issues/35
notifications:
  email:
    - nicolas.matentzoglu@gmail.com
