name: Run and deploy release
on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.4
    strategy:
      max-parallel: 1
      
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Update release files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx10G' GITHUB_ACTION=true prepare_release_fast
      
      - name: Run release
        uses: gaoDean/action-gh-release@6b61bb5648ddc1241deb73ea6b72c3a1e1f9e445
        with:
          generate_release_notes: true
          draft: true
          tag_name: v${{ steps.date.outputs.date }}
          files: |
            mp.owl
            mp.obo
            mp.json
            mp-base.owl
            mp-base.obo
            mp-base.json
            mp-full.owl
            mp-full.obo
            mp-full.json
            mp-international.owl
            src/translations/mp-ja.babelon.tsv
            src/translations/mp-ja.owl
            src/translations/mp-ja-changed.babelon.tsv
            src/translations/mp-ja-not-translated.babelon.tsv
            mp-simple-non-classified.owl
            mp-simple-non-classified.obo
            mp-simple-non-classified.json
