name: Run and deploy release
on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.1
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: work around permission issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Update release files
        run: cd src/ontology/ && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' GITHUB_ACTION=true prepare_release_fast
      
      - name: Run release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            mp.owl
            mp.obo
            mp.json
            mp-base.owl
            mp-base.obo
            mp-base.json
            mp-full.owl
            mp-full.obo
            mp-full.json
            mp-simple-non-classified.owl
            mp-simple-non-classified.obo
            mp-simple-non-classified.json
